import { Autocomplete } from '@react-google-maps/api';
import { useAuth } from '@clerk/clerk-react';
import { Briefcase, CheckSquare, Cloud, Download, MapPin, Printer, Shirt, Sparkles, Thermometer, Umbrella, Wand2 } from 'lucide-react';
import React, { useEffect, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import { useDispatch, useSelector } from 'react-redux';

import { useGoogleMaps } from '../../context/GoogleMapsContext';
import { generatePackingList, clearPackingList } from '../../redux/slices/aiSlice';

function AiPackagePlanner() {
  const autocompleteRef = useRef(null);

  const [formData, setFormData] = useState({
    destination: 'Goa, India',
    travelDate: '2025-01-15',
    tripDuration: '5',
    tripType: 'leisure',
    gender: 'unisex',
    activities: ['Sightseeing', 'Swimming']
  });

  const dispatch = useDispatch();
  const { getToken } = useAuth();
  const { packingList, isGenerating, error } = useSelector((state) => state.ai);
  const { isLoaded } = useGoogleMaps();

  // Clear packing list on unmount
  useEffect(() => {
    return () => {
      dispatch(clearPackingList());
    };
  }, [dispatch]);

  const activityOptions = [
    'Sightseeing', 'Hiking', 'Swimming', 'Camping', 'Business', 'Nightlife', 'Photography', 'Skiing'
  ];

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const toggleActivity = (activity) => {
    setFormData(prev => ({
      ...prev,
      activities: prev.activities.includes(activity)
        ? prev.activities.filter(a => a !== activity)
        : [...prev.activities, activity]
    }));
  };

  const handleGenerateList = async (e) => {
    e.preventDefault();

    try {
      await dispatch(generatePackingList({
        getToken,
        packingData: formData
      })).unwrap();
      toast.success('Packing list generated successfully!');
    } catch (error) {
      toast.error(error || 'Failed to generate packing list');
    }
  };

  const handleDownloadList = () => {
    if (!packingList) return;

    let content = `Packing List for ${formData.destination}\n`;
    content += `${'='.repeat(content.length)}\n\n`;
    content += `Trip Dates: ${formData.travelDate} (${formData.tripDuration} Days)\n`;
    content += `Weather Forecast: ${packingList.weather.condition}, ${packingList.weather.temp}\n`;
    content += `Note: ${packingList.weather.advice}\n\n`;
    content += `${'='.repeat(50)}\n\n`;

    packingList.categories.forEach(category => {
      content += `[ ${category.name} ]\n`;
      category.items.forEach(item => {
        content += `[ ] ${item}\n`;
      });
      content += `\n`;
    });

    content += `\n${'='.repeat(50)}\n`;
    content += `Generated by TravelBuddy AI Packaging Planner\n`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `PackingList_${formData.destination.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast.success('List downloaded successfully!');
  };

  const onAutocompleteLoad = (autocomplete) => {
    autocompleteRef.current = autocomplete;
  };

  const onPlaceChanged = () => {
    const place = autocompleteRef.current?.getPlace();
    if (place?.formatted_address || place?.name) {
      const destination = place.formatted_address || place.name;
      setFormData(prev => ({ ...prev, destination }));
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-blue-50 pt-28 pb-16 px-4">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 bg-gradient-to-r from-purple-100 to-blue-100 px-4 py-2 rounded-full mb-4">
            <Briefcase className="text-purple-600" size={20} />
            <span className="text-purple-700 font-semibold text-sm">Smart Packing Assistant</span>
          </div>
          <h1 className="text-5xl font-bold bg-gradient-to-r from-purple-600 via-blue-600 to-purple-600 bg-clip-text text-transparent mb-4">
            AI Packaging Planner
          </h1>
          <p className="text-gray-600 text-lg max-w-2xl mx-auto">
            Get a personalized packing checklist based on your destination, weather, and planned activities.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Form Section */}
          <div className="bg-white rounded-3xl shadow-xl border border-gray-100 p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 bg-purple-100 rounded-xl">
                <Shirt className="text-purple-600" size={24} />
              </div>
              <h2 className="text-2xl font-bold text-gray-900">Trip Details</h2>
            </div>

            <form onSubmit={handleGenerateList} className="space-y-6">
              {/* Destination */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Destination
                </label>
                {isLoaded ? (
                  <Autocomplete onLoad={onAutocompleteLoad} onPlaceChanged={onPlaceChanged}>
                    <div className="relative">
                      <MapPin className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 z-10" size={20} />
                      <input
                        type="text"
                        name="destination"
                        value={formData.destination}
                        onChange={handleInputChange}
                        placeholder="Where are you traveling?"
                        className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                        required
                      />
                    </div>
                  </Autocomplete>
                ) : (
                  <div className="relative">
                    <MapPin className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                    <input
                      type="text"
                      className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl bg-gray-50"
                      placeholder="Loading Maps..."
                      disabled
                    />
                  </div>
                )}
              </div>

              {/* Trip Dates & Duration */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">Start Date</label>
                  <input
                    type="date"
                    name="travelDate"
                    value={formData.travelDate}
                    onChange={handleInputChange}
                    min={new Date().toISOString().split('T')[0]}
                    className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">Duration (Days)</label>
                  <input
                    type="number"
                    name="tripDuration"
                    value={formData.tripDuration}
                    onChange={handleInputChange}
                    min="1"
                    className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                    required
                  />
                </div>
              </div>

              {/* Traveler Type & Gender */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">Types of Trip</label>
                  <select
                    name="tripType"
                    value={formData.tripType}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-transparent bg-white"
                  >
                    <option value="leisure">Leisure / Vacation</option>
                    <option value="business">Business</option>
                    <option value="adventure">Adventure</option>
                    <option value="family">Family</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">Gender</label>
                  <select
                    name="gender"
                    value={formData.gender}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-transparent bg-white"
                  >
                    <option value="unisex">Prefer not to say</option>
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                  </select>
                </div>
              </div>

               {/* Activities */}
               <div>
                <label className="block text-sm font-semibold text-gray-700 mb-3">
                  Planned Activities
                </label>
                <div className="flex flex-wrap gap-2">
                  {activityOptions.map(activity => (
                    <button
                      key={activity}
                      type="button"
                      onClick={() => toggleActivity(activity)}
                      className={`px-4 py-2 rounded-full text-sm font-medium transition-all duration-200 ${
                        formData.activities.includes(activity)
                          ? 'bg-purple-600 text-white shadow-lg shadow-purple-500/30'
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      {activity}
                    </button>
                  ))}
                </div>
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                disabled={isGenerating}
                className="w-full bg-gradient-to-r from-purple-600 to-blue-600 text-white py-4 rounded-xl font-semibold text-lg hover:shadow-2xl hover:shadow-purple-500/30 hover:-translate-y-0.5 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isGenerating ? (
                   <>
                   <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent"></div>
                   Checking weather & generating list...
                 </>
                ) : (
                  <>
                    <Wand2 size={20} />
                    Generate Packing List
                  </>
                )}
              </button>
            </form>
          </div>

          {/* Results Section */}
          <div className="bg-gradient-to-br from-purple-50 via-white to-blue-50 rounded-3xl shadow-xl border-2 border-purple-100 p-8">
            {!packingList ? (
               <div className="h-full flex flex-col items-center justify-center text-center p-8">
               <div className="bg-gradient-to-br from-purple-100 to-blue-100 p-6 rounded-2xl mb-6 animate-pulse">
                 <Briefcase size={48} className="text-purple-600" />
               </div>
               <h3 className="text-2xl font-bold mb-3 text-gray-800">Ready to Pack?</h3>
               <p className="text-gray-600 max-w-md">
                 Our AI will analyze the weather forecast for your dates and create a comprehensive checklist so you don't forget the essentials.
               </p>
             </div>
            ) : (
              <div className="space-y-6 h-full flex flex-col animate-in fade-in duration-500">
                {/* Weather Summary */}
                <div className="bg-white rounded-2xl p-6 border border-blue-100 shadow-sm">
                   <div className="flex items-start justify-between">
                     <div>
                       <h3 className="text-lg font-bold text-gray-800 flex items-center gap-2">
                         <Cloud className="text-blue-500" size={20} />
                         Weather Forecast
                       </h3>
                       <p className="text-3xl font-bold text-gray-900 mt-2">{packingList.weather.temp}</p>
                       <p className="text-blue-600 font-medium">{packingList.weather.condition}</p>
                     </div>
                     <div className="bg-blue-50 p-3 rounded-xl">
                        <Thermometer className="text-blue-600" size={24} />
                     </div>
                   </div>
                   <p className="text-sm text-gray-600 mt-4 border-t border-gray-100 pt-3">
                     💡 {packingList.weather.advice}
                   </p>
                </div>

                {/* Packing Categories */}
                <div className="flex-1 overflow-y-auto pr-2 space-y-4 max-h-[400px] scrollbar-thin scrollbar-thumb-purple-200">
                  {packingList.categories.map((category, idx) => (
                    <div key={idx} className="bg-white/80 backdrop-blur-sm rounded-xl p-5 border border-purple-100">
                      <h4 className="font-bold text-gray-800 mb-3 flex items-center gap-2">
                         <span className="w-2 h-2 rounded-full bg-purple-500"></span>
                         {category.name}
                      </h4>
                      <div className="grid grid-cols-2 gap-2">
                        {category.items.map((item, itemIdx) => (
                          <div key={itemIdx} className="flex items-center gap-2 text-gray-600 text-sm">
                            <CheckSquare size={16} className="text-purple-300" />
                            {item}
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>

                <button
                  onClick={handleDownloadList}
                  className="w-full mt-auto bg-white border-2 border-purple-100 text-purple-600 py-3 rounded-xl font-semibold hover:bg-purple-50 transition-colors flex items-center justify-center gap-2"
                >
                  <Download size={20} />
                  Download Checklist
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default AiPackagePlanner;
