import { Autocomplete } from '@react-google-maps/api';
import { useAuth } from '@clerk/clerk-react';
import { Calendar, Clock, DollarSign, Download, MapPin, Sparkles, Users, Wand2 } from 'lucide-react';
import React, { useEffect, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import { useDispatch, useSelector } from 'react-redux';

import { useGoogleMaps } from '../../context/GoogleMapsContext';
import { clearTripPlan, generateTripPlan } from '../../redux/slices/aiSlice';

function AiTripPlanner() {
  const autocompleteRef = useRef(null);

  const [formData, setFormData] = useState({
    destination: 'Goa, India',
    startDate: '2025-01-15',
    endDate: '2025-01-20',
    budget: '75000',
    travelers: '2',
    interests: ['Beach', 'Food', 'Nightlife', 'Relaxation'],
    travelStyle: 'balanced'
  });

  const dispatch = useDispatch();
  const { getToken } = useAuth();
  const { tripPlan, isGenerating, error } = useSelector((state) => state.ai);
  const { isLoaded } = useGoogleMaps();

  const interestOptions = [
    'Adventure', 'Culture', 'Food', 'Nature', 'Nightlife',
    'Photography', 'Shopping', 'Relaxation', 'History', 'Beach'
  ];

  const travelStyles = [
    { id: 'budget', label: 'Budget Friendly', icon: '💰' },
    { id: 'balanced', label: 'Balanced', icon: '⚖️' },
    { id: 'luxury', label: 'Luxury', icon: '✨' }
  ];

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const toggleInterest = (interest) => {
    setFormData(prev => ({
      ...prev,
      interests: prev.interests.includes(interest)
        ? prev.interests.filter(i => i !== interest)
        : [...prev.interests, interest]
    }));
  };

  const handleGeneratePlan = async (e) => {
    e.preventDefault();

    try {
      await dispatch(generateTripPlan({
        getToken,
        tripData: formData
      })).unwrap();

      toast.success('Trip plan generated successfully!');
    } catch (error) {
      toast.error(error || 'Failed to generate trip plan');
    }
  };

  const handleDownloadItinerary = () => {
    if (!tripPlan) return;

    // Create formatted text content
    let content = `${tripPlan.title}\n`;
    content += `${'='.repeat(tripPlan.title.length)}\n\n`;
    content += `Trip Duration: ${tripPlan.days} Days\n`;
    content += `Destination: ${formData.destination}\n`;
    content += `Dates: ${formData.startDate} to ${formData.endDate}\n`;
    content += `Budget: ₹${formData.budget} INR\n`;
    content += `Travelers: ${formData.travelers} ${formData.travelers === '1' ? 'Person' : 'People'}\n`;
    content += `Travel Style: ${formData.travelStyle}\n`;
    content += `Interests: ${formData.interests.join(', ')}\n\n`;
    content += `${'='.repeat(50)}\n\n`;

    // Add day-by-day itinerary
    tripPlan.itinerary?.forEach((day) => {
      content += `DAY ${day.day}: ${day.title}\n`;
      content += `${'-'.repeat(40)}\n`;
      day.activities?.forEach((activity, idx) => {
        content += `${idx + 1}. ${activity}\n`;
      });
      content += `\n`;
    });

    content += `\n${'='.repeat(50)}\n`;
    content += `Generated by TravelBuddy AI Trip Planner\n`;
    content += `Date: ${new Date().toLocaleDateString()}\n`;

    // Create blob and download
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${tripPlan.title.replace(/\s+/g, '_')}_Itinerary.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast.success('Itinerary downloaded successfully!');
  };

  const onAutocompleteLoad = (autocomplete) => {
    autocompleteRef.current = autocomplete;
  };

  const onPlaceChanged = () => {
    const place = autocompleteRef.current?.getPlace();
    if (place?.formatted_address || place?.name) {
      const destination = place.formatted_address || place.name;
      setFormData(prev => ({ ...prev, destination }));
    }
  };

  // Clear trip plan when component unmounts
  useEffect(() => {
    return () => {
      dispatch(clearTripPlan());
    };
  }, [dispatch]);

  // Prevent past dates
  const today = new Date().toISOString().split('T')[0];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-sky-50 pt-28 pb-16 px-4">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 bg-gradient-to-r from-blue-100 to-sky-100 px-4 py-2 rounded-full mb-4">
            <Sparkles className="text-blue-600" size={20} />
            <span className="text-blue-700 font-semibold text-sm">AI-Powered Trip Planning</span>
          </div>
          <h1 className="text-5xl font-bold bg-gradient-to-r from-blue-600 via-sky-600 to-blue-600 bg-clip-text text-transparent mb-4">
            Plan Your Perfect Trip
          </h1>
          <p className="text-gray-600 text-lg max-w-2xl mx-auto">
            Tell us your preferences and let our AI create a personalized itinerary tailored just for you
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Form Section */}
          <div className="bg-white rounded-3xl shadow-xl border border-gray-100 p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 bg-blue-100 rounded-xl">
                <Wand2 className="text-blue-600" size={24} />
              </div>
              <h2 className="text-2xl font-bold text-gray-900">Trip Details</h2>
            </div>

            <form onSubmit={handleGeneratePlan} className="space-y-6">
              {/* Destination */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Destination
                </label>
                {isLoaded ? (
                  <Autocomplete onLoad={onAutocompleteLoad} onPlaceChanged={onPlaceChanged}>
                    <div className="relative">
                      <MapPin className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 z-10" size={20} />
                      <input
                        type="text"
                        name="destination"
                        value={formData.destination}
                        onChange={handleInputChange}
                        placeholder="Search destination (e.g., Paris, Tokyo)"
                        className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
                        required
                      />
                    </div>
                  </Autocomplete>
                ) : (
                  <div className="relative">
                    <MapPin className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                    <input
                      type="text"
                      className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl bg-gray-50"
                      placeholder="Loading Maps..."
                      disabled
                    />
                  </div>
                )}
              </div>

              {/* Dates */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">Start Date</label>
                  <input
                    type="date"
                    name="startDate"
                    value={formData.startDate}
                    onChange={handleInputChange}
                    min={today}
                    className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">End Date</label>
                  <input
                    type="date"
                    name="endDate"
                    value={formData.endDate}
                    onChange={handleInputChange}
                     min={formData.startDate || today}
                    className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    required
                  />
                </div>
              </div>

              {/* Budget & Travelers */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">Budget (₹ INR)</label>
                  <div className="relative">
                    <DollarSign className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                    <input
                      type="number"
                      name="budget"
                      value={formData.budget}
                      onChange={handleInputChange}
                      placeholder="e.g., 50000"
                      className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      required
                    />
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">Travelers</label>
                  <div className="relative">
                    <Users className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                    <select
                      name="travelers"
                      value={formData.travelers}
                      onChange={handleInputChange}
                      className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent appearance-none bg-white"
                    >
                      {[1, 2, 3, 4, 5, 6].map(num => (
                        <option key={num} value={num}>{num} {num === 1 ? 'Person' : 'People'}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>

              {/* Travel Style */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-3">Travel Style</label>
                <div className="grid grid-cols-3 gap-3">
                  {travelStyles.map(style => (
                    <button
                      key={style.id}
                      type="button"
                      onClick={() => setFormData(prev => ({ ...prev, travelStyle: style.id }))}
                      className={`p-4 rounded-xl border-2 transition-all duration-200 ${
                        formData.travelStyle === style.id
                          ? 'border-blue-500 bg-blue-50 shadow-md'
                          : 'border-gray-200 hover:border-blue-300 bg-white'
                      }`}
                    >
                      <div className="text-2xl mb-1">{style.icon}</div>
                      <div className="text-sm font-medium text-gray-700">{style.label}</div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Interests */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-3">
                  Your Interests (Select multiple)
                </label>
                <div className="flex flex-wrap gap-2">
                  {interestOptions.map(interest => (
                    <button
                      key={interest}
                      type="button"
                      onClick={() => toggleInterest(interest)}
                      className={`px-4 py-2 rounded-full text-sm font-medium transition-all duration-200 ${
                        formData.interests.includes(interest)
                          ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/30'
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      {interest}
                    </button>
                  ))}
                </div>
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                disabled={isGenerating}
                className="w-full bg-gradient-to-r from-blue-500 to-sky-600 text-white py-4 rounded-xl font-semibold text-lg hover:shadow-2xl hover:shadow-blue-500/30 hover:-translate-y-0.5 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isGenerating ? (
                   <>
                   <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent"></div>
                   Generating Your Perfect Trip...
                 </>
                ) : (
                  <>
                    <Sparkles size={20} />
                    Generate AI Trip Plan
                  </>
                )}
              </button>
            </form>
          </div>

          {/* Results Section */}
          <div className="bg-gradient-to-br from-blue-50 via-white to-sky-50 rounded-3xl shadow-xl border-2 border-blue-100 p-8">
            {!tripPlan ? (
               <div className="h-full flex flex-col items-center justify-center text-center p-8">
               <div className="bg-gradient-to-br from-blue-100 to-sky-100 p-6 rounded-2xl mb-6 animate-pulse">
                 <Sparkles size={48} className="text-blue-600" />
               </div>
               <h3 className="text-2xl font-bold mb-3 text-gray-800">Your AI Trip Awaits</h3>
               <p className="text-gray-600 max-w-md">
                 Fill in your preferences and our AI will create a personalized itinerary with recommendations for activities, restaurants, and hidden gems.
               </p>
             </div>
            ) : (
              <div className="space-y-6 h-full flex flex-col animate-in fade-in duration-500">
                {/* Trip Header Summary */}
                <div className="bg-white rounded-2xl p-6 border border-blue-100 shadow-sm">
                   <div className="flex items-start justify-between">
                     <div>
                       <h3 className="text-xl font-bold text-gray-800 flex items-center gap-2">
                         <MapPin className="text-blue-500" size={20} />
                         {tripPlan.title}
                       </h3>
                       <div className="flex items-center gap-4 text-gray-600 mt-2 text-sm">
                            <span className="flex items-center gap-1"><Clock size={16}/> {tripPlan.days} Days</span>
                            <span className="flex items-center gap-1"><Users size={16}/> {formData.travelers} Travelers</span>
                       </div>
                     </div>
                     <div className="bg-blue-50 p-3 rounded-xl">
                        <DollarSign className="text-blue-600" size={24} />
                     </div>
                   </div>
                </div>

                {/* Day-by-Day Itinerary */}
                <div className="flex-1 overflow-y-auto pr-2 space-y-4 max-h-[400px] scrollbar-thin scrollbar-thumb-blue-200">
                  {tripPlan.itinerary?.map((day) => (
                    <div key={day.day} className="bg-white/80 backdrop-blur-sm rounded-xl p-5 border border-blue-100">
                      <h4 className="font-bold text-gray-800 mb-3 flex items-center gap-3">
                         <span className="bg-blue-500 text-white px-3 py-1 rounded-full text-sm">Day {day.day}</span>
                         {day.title}
                      </h4>
                      <ul className="space-y-2 relative border-l-2 border-blue-100 ml-3 pl-4">
                        {day.activities?.map((activity, idx) => (
                           <li key={idx} className="text-gray-600 text-sm relative">
                             <div className="absolute -left-[21px] top-1.5 w-2.5 h-2.5 rounded-full bg-blue-300 border-2 border-white"></div>
                             {activity}
                           </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>

                <button
                  onClick={handleDownloadItinerary}
                  className="w-full mt-auto bg-white border-2 border-blue-100 text-blue-600 py-3 rounded-xl font-semibold hover:bg-blue-50 transition-colors flex items-center justify-center gap-2"
                >
                  <Download size={20} />
                  Download Full Itinerary
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default AiTripPlanner;