import { Autocomplete } from '@react-google-maps/api';
import { useAuth } from '@clerk/clerk-react';
import { Calendar, Clock, DollarSign, Download, MapPin, Sparkles, Users, Wand2 } from 'lucide-react';
import React, { useEffect, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import { useDispatch, useSelector } from 'react-redux';

import { useGoogleMaps } from '../../context/GoogleMapsContext';
import { clearTripPlan, generateTripPlan } from '../../redux/slices/aiSlice';

function AiTripPlanner() {
  const autocompleteRef = useRef(null);

  const [formData, setFormData] = useState({
    destination: 'Goa, India',
    startDate: '2025-01-15',
    endDate: '2025-01-20',
    budget: '75000',
    travelers: '2',
    interests: ['Beach', 'Food', 'Nightlife', 'Relaxation'],
    travelStyle: 'balanced'
  });

  const dispatch = useDispatch();
  const { getToken } = useAuth();
  const { tripPlan, isGenerating, error } = useSelector((state) => state.ai);
  const { isLoaded } = useGoogleMaps();

  const interestOptions = [
    'Adventure', 'Culture', 'Food', 'Nature', 'Nightlife',
    'Photography', 'Shopping', 'Relaxation', 'History', 'Beach'
  ];

  const travelStyles = [
    { id: 'budget', label: 'Budget Friendly', icon: '💰' },
    { id: 'balanced', label: 'Balanced', icon: '⚖️' },
    { id: 'luxury', label: 'Luxury', icon: '✨' }
  ];

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const toggleInterest = (interest) => {
    setFormData(prev => ({
      ...prev,
      interests: prev.interests.includes(interest)
        ? prev.interests.filter(i => i !== interest)
        : [...prev.interests, interest]
    }));
  };

  const handleGeneratePlan = async (e) => {
    e.preventDefault();

    try {
      const result = await dispatch(generateTripPlan({
        getToken,
        tripData: formData
      })).unwrap();

      toast.success('Trip plan generated successfully!');
    } catch (error) {
      toast.error(error || 'Failed to generate trip plan');
    }
  };

  const handleDownloadItinerary = () => {
    if (!tripPlan) return;

    // Create formatted text content
    let content = `${tripPlan.title}\n`;
    content += `${'='.repeat(tripPlan.title.length)}\n\n`;
    content += `Trip Duration: ${tripPlan.days} Days\n`;
    content += `Destination: ${formData.destination}\n`;
    content += `Dates: ${formData.startDate} to ${formData.endDate}\n`;
    content += `Budget: ₹${formData.budget} INR\n`;
    content += `Travelers: ${formData.travelers} ${formData.travelers === '1' ? 'Person' : 'People'}\n`;
    content += `Travel Style: ${formData.travelStyle}\n`;
    content += `Interests: ${formData.interests.join(', ')}\n\n`;
    content += `${'='.repeat(50)}\n\n`;

    // Add day-by-day itinerary
    tripPlan.itinerary?.forEach((day) => {
      content += `DAY ${day.day}: ${day.title}\n`;
      content += `${'-'.repeat(40)}\n`;
      day.activities?.forEach((activity, idx) => {
        content += `${idx + 1}. ${activity}\n`;
      });
      content += `\n`;
    });

    content += `\n${'='.repeat(50)}\n`;
    content += `Generated by TravelBuddy AI Trip Planner\n`;
    content += `Date: ${new Date().toLocaleDateString()}\n`;

    // Create blob and download
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${tripPlan.title.replace(/\s+/g, '_')}_Itinerary.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast.success('Itinerary downloaded successfully!');
  };

  const onAutocompleteLoad = (autocomplete) => {
    autocompleteRef.current = autocomplete;
  };

  const onPlaceChanged = () => {
    const place = autocompleteRef.current?.getPlace();
    if (place?.formatted_address || place?.name) {
      const destination = place.formatted_address || place.name;
      setFormData(prev => ({ ...prev, destination }));
    }
  };

  // Clear trip plan when component unmounts
  useEffect(() => {
    return () => {
      dispatch(clearTripPlan());
    };
  }, [dispatch]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-amber-50 via-white to-orange-50 pt-28 pb-16 px-4">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 bg-gradient-to-r from-amber-100 to-orange-100 px-4 py-2 rounded-full mb-4">
            <Sparkles className="text-amber-600" size={20} />
            <span className="text-amber-700 font-semibold text-sm">AI-Powered Trip Planning</span>
          </div>
          <h1 className="text-5xl font-bold bg-gradient-to-r from-amber-600 via-orange-600 to-amber-600 bg-clip-text text-transparent mb-4">
            Plan Your Perfect Trip
          </h1>
          <p className="text-gray-600 text-lg max-w-2xl mx-auto">
            Tell us your preferences and let our AI create a personalized itinerary tailored just for you
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Form Section */}
          <div className="bg-white rounded-3xl shadow-xl border border-gray-100 p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 bg-amber-100 rounded-xl">
                <Wand2 className="text-amber-600" size={24} />
              </div>
              <h2 className="text-2xl font-bold text-gray-900">Trip Details</h2>
            </div>

            <form onSubmit={handleGeneratePlan} className="space-y-6">
              {/* Destination */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Where do you want to go?
                </label>
                {isLoaded ? (
                  <Autocomplete onLoad={onAutocompleteLoad} onPlaceChanged={onPlaceChanged}>
                    <div className="relative">
                      <MapPin className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 z-10" size={20} />
                      <input
                        type="text"
                        name="destination"
                        value={formData.destination}
                        onChange={handleInputChange}
                        placeholder="Search destination (e.g., Paris, Tokyo)"
                        className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-all"
                        required
                      />
                    </div>
                  </Autocomplete>
                ) : (
                  <div className="relative">
                    <MapPin className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                    <input
                      type="text"
                      name="destination"
                      value={formData.destination}
                      onChange={handleInputChange}
                      placeholder="Loading Google Maps..."
                      className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-all"
                      disabled
                    />
                  </div>
                )}
              </div>

              {/* Dates */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    Start Date
                  </label>
                  <div className="relative">
                    <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                    <input
                      type="date"
                      name="startDate"
                      value={formData.startDate}
                      onChange={handleInputChange}
                      className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-transparent"
                      required
                    />
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    End Date
                  </label>
                  <div className="relative">
                    <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                    <input
                      type="date"
                      name="endDate"
                      value={formData.endDate}
                      onChange={handleInputChange}
                      className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-transparent"
                      required
                    />
                  </div>
                </div>
              </div>

              {/* Budget & Travelers */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    Budget (₹ INR)
                  </label>
                  <div className="relative">
                    <DollarSign className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                    <input
                      type="number"
                      name="budget"
                      value={formData.budget}
                      onChange={handleInputChange}
                      placeholder="e.g., 50000"
                      className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-transparent"
                      required
                    />
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    Travelers
                  </label>
                  <div className="relative">
                    <Users className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                    <select
                      name="travelers"
                      value={formData.travelers}
                      onChange={handleInputChange}
                      className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-transparent appearance-none bg-white"
                    >
                      {[1, 2, 3, 4, 5, 6].map(num => (
                        <option key={num} value={num}>{num} {num === 1 ? 'Person' : 'People'}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>

              {/* Travel Style */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-3">
                  Travel Style
                </label>
                <div className="grid grid-cols-3 gap-3">
                  {travelStyles.map(style => (
                    <button
                      key={style.id}
                      type="button"
                      onClick={() => setFormData(prev => ({ ...prev, travelStyle: style.id }))}
                      className={`p-4 rounded-xl border-2 transition-all duration-200 ${
                        formData.travelStyle === style.id
                          ? 'border-amber-500 bg-amber-50 shadow-md'
                          : 'border-gray-200 hover:border-amber-300 bg-white'
                      }`}
                    >
                      <div className="text-2xl mb-1">{style.icon}</div>
                      <div className="text-sm font-medium text-gray-700">{style.label}</div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Interests */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-3">
                  Your Interests (Select multiple)
                </label>
                <div className="flex flex-wrap gap-2">
                  {interestOptions.map(interest => (
                    <button
                      key={interest}
                      type="button"
                      onClick={() => toggleInterest(interest)}
                      className={`px-4 py-2 rounded-full text-sm font-medium transition-all duration-200 ${
                        formData.interests.includes(interest)
                          ? 'bg-amber-600 text-white shadow-lg shadow-amber-500/30'
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      {interest}
                    </button>
                  ))}
                </div>
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                disabled={isGenerating}
                className="w-full bg-gradient-to-r from-amber-500 to-orange-600 text-white py-4 rounded-xl font-semibold text-lg hover:shadow-2xl hover:shadow-amber-500/30 hover:-translate-y-0.5 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isGenerating ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent"></div>
                    Generating Your Perfect Trip...
                  </>
                ) : (
                  <>
                    <Sparkles size={20} />
                    Generate AI Trip Plan
                  </>
                )}
              </button>
            </form>
          </div>

          {/* Preview/Results Section */}
          <div className="bg-gradient-to-br from-orange-100 via-orange-50 to-amber-100 rounded-3xl shadow-2xl border-2 border-orange-200 p-8">
            {!tripPlan ? (
              <div className="h-full flex flex-col items-center justify-center text-center">
                <div className="bg-gradient-to-br from-orange-200 to-amber-200 p-6 rounded-2xl mb-6">
                  <Sparkles size={48} className="text-orange-600" />
                </div>
                <h3 className="text-2xl font-bold mb-3 text-gray-800">Your AI Trip Awaits</h3>
                <p className="text-gray-600 max-w-md">
                  Fill in your preferences and our AI will create a personalized itinerary with recommendations
                  for activities, restaurants, and hidden gems.
                </p>
              </div>
            ) : (
              <div className="space-y-6 animate-in fade-in duration-500">
                <div className="bg-gradient-to-br from-orange-200 to-amber-200 rounded-2xl p-6 border border-orange-300">
                  <h3 className="text-3xl font-bold mb-2 text-gray-800">{tripPlan.title}</h3>
                  <div className="flex items-center gap-4 text-gray-700">
                    <div className="flex items-center gap-2">
                      <Clock size={18} />
                      <span>{tripPlan.days} Days</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Users size={18} />
                      <span>{formData.travelers} Travelers</span>
                    </div>
                  </div>
                </div>

                <div className="space-y-4 max-h-[500px] overflow-y-auto pr-2 scrollbar-thin scrollbar-thumb-orange-300 scrollbar-track-orange-100">
                  <h4 className="text-xl font-semibold text-gray-800 sticky top-0 bg-gradient-to-br from-orange-100 via-orange-50 to-amber-100 py-2 z-10">Day-by-Day Itinerary</h4>
                  {tripPlan.itinerary?.map((day) => (
                    <div key={day.day} className="bg-white/80 backdrop-blur-sm rounded-xl p-5 border border-orange-200 shadow-sm">
                      <div className="flex items-center gap-3 mb-3">
                        <div className="bg-gradient-to-r from-orange-500 to-amber-500 text-white px-3 py-1 rounded-full text-sm font-semibold">
                          Day {day.day}
                        </div>
                        <h5 className="font-semibold text-lg text-gray-800">{day.title}</h5>
                      </div>
                      <ul className="space-y-2">
                        {day.activities?.map((activity, idx) => (
                          <li key={idx} className="flex items-center gap-2 text-gray-700">
                            <div className="w-1.5 h-1.5 bg-orange-500 rounded-full"></div>
                            {activity}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>

                <button
                  onClick={handleDownloadItinerary}
                  className="w-full bg-gradient-to-r from-amber-500 to-orange-600 text-white py-3 rounded-xl font-semibold hover:shadow-lg hover:shadow-orange-500/30 hover:-translate-y-0.5 transition-all flex items-center justify-center gap-2"
                >
                  <Download size={20} />
                  Download Full Itinerary
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Features Section */}
        <div className="mt-16 grid md:grid-cols-3 gap-6">
          {[
            { icon: Sparkles, title: 'AI-Powered', desc: 'Smart recommendations based on your preferences' },
            { icon: Clock, title: 'Save Time', desc: 'Get a complete itinerary in seconds' },
            { icon: MapPin, title: 'Local Insights', desc: 'Discover hidden gems and local favorites' }
          ].map((feature, idx) => (
            <div key={idx} className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm hover:shadow-xl transition-shadow">
              <div className="bg-amber-100 w-12 h-12 rounded-xl flex items-center justify-center mb-4">
                <feature.icon className="text-amber-600" size={24} />
              </div>
              <h3 className="font-bold text-lg mb-2 text-gray-900">{feature.title}</h3>
              <p className="text-gray-600">{feature.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default AiTripPlanner;